development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: iEmerge_production_development
  pool: 5
  username: iemerge
  password: ProductioniEmergePassword
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: iEmerge_production_test
  pool: 5
  username: iemerge
  password: ProductioniEmergePassword
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: iEmerge_production
  pool: 5
  username: iemerge
  password: ProductioniEmergePassword
  host: localhost
