development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: iEmerge_staging_development
  pool: 5
  username: iemerge
  password: StagingiEmergePassword
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: iEmerge_staging_test
  pool: 5
  username: iemerge
  password: StagingiEmergePassword
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: iEmerge_staging
  pool: 5
  username: iemerge
  password: StagingiEmergePassword
  host: localhost
